import sys
from pathlib import Path
from io import FileIO, StringIO
from util.lexer import Lexer
from util.parser import Parser
from util.nodes import Node, Document, LexicalNode
from util.token import TK, Token
from util.logging import get_logger


logger = get_logger(__name__)


class Comment(LexicalNode):
    def __init__(self, tokens: list[Token], parent: Node = None):
        LexicalNode.__init__(self, tokens, parent)

        self.text: str = self.raw().strip()


class Key(LexicalNode):
    def __init__(self, tokens: list[Token], parent: Node = None):
        LexicalNode.__init__(self, tokens, parent)

        self.name: str = self.raw().strip()

        if self.name not in ODF.Keys:
            logger.warning(f'Key name "{self.name}" is not known.')


class Value(LexicalNode):
    def __init__(self, tokens: list[Token], parent: Node = None):
        LexicalNode.__init__(self, tokens, parent)

        self.value: str = self.raw().strip()


class Section(LexicalNode):
    def __init__(self, tokens: list[Token], parent: Node = None):
        LexicalNode.__init__(self, tokens, parent)

        self.name: str = self.raw().strip()

        if self.name not in ODF.Sections:
            logger.warning(f'Section name "{self.name}" is not known.')


class ODF(Document, Parser):
    Sections = [
       'ExplosionClass',
       'GameObjectClass',
       'InputSystem',
       'InstanceProperties',
       'OrdnanceClass',
       'Properties',
       'WeaponClass',
    ]

    Keys = [
       'abandon',
       'Acceleration',
       'Acceleraton',
       'AcquiredTargetSound',
       'ActiveRotateNode',
       'ActiveSpinNode',
       'AddHealth',
       'AddonAttachJoint',
       'AddShield',
       'AddShieldOff',
       'AddSpringBody',
       'AfterburnerOffSound',
       'AfterburnerOnSound',
       'AfterburnerSpeed',
       'AIDriverGetInSound',
       'AIDriverGetOutSound',
       'AIFieldFollowSound',
       'AIFieldHoldSound',
       'AIFieldMoveOutSound',
       'AIGunnerAllClearSound',
       'AIGunnerGetInSound',
       'AIGunnerGetOutSound',
       'AIGunnerSteadySound',
       'AimAzimuth',
       'AimDistance',
       'AimElevation',
       'AimerNodeName',
       'AimerPitchLimits',
       'AimerPitchLimts',
       'AimerYawLimits',
       'AimerYawLimts',
       'AimFactorMove',
       'AimFactorPostureCrouch',
       'AimFactorPostureProne',
       'AimFactorPostureSpecial',
       'AimFactorPostureStand',
       'AimFactorStrafe',
       'AimTension',
       'AimValue',
       'AIPassengerGetInSound',
       'AIPassengerGetOutSound',
       'AIPassengerMoveOutSound',
       'AIPassengerStopSound',
       'AIResponseNosirSound',
       'AIResponseYessirSound',
       'AISCDriverGetInSound',
       'AISCDriverGetOutSound',
       'AISCFieldFollowSound',
       'AISCFieldHoldSound',
       'AISCFieldMoveOutSound',
       'AISCGunnerAllClearSound',
       'AISCGunnerGetInSound',
       'AISCGunnerGetOutSound',
       'AISCGunnerSteadySound',
       'AISCPassengerGetInSound',
       'AISCPassengerGetOutSound',
       'AISCPassengerMoveOutSound',
       'AISCPassengerStopSound',
       'AISCResponseNosirSound',
       'AISCResponseYessirSound',
       'AISizeType',
       'AlignVertical',
       'AllMusic',
       'AllyCount',
       'AllyPath',
       'Alpha',
       'Ambient2Sound',
       'AmbientSound',
       'AnimalHealth',
       'AnimalScale',
       'AnimatedAddon',
       'AnimatedPilotPosition',
       'Animation',
       'AnimationAddon',
       'AnimationBank',
       'AnimationExtraFile',
       'AnimationLowRes',
       'AnimationName',
       'AnimationTrigger',
       'ApproachingTargetSound',
       'ArmName',
       'ArmorScale',
       'AttachDynamic',
       'AttachedMesh',
       'AttachEffect',
       'AttachOdf',
       'AttachToHardpoint',
       'AttachToHardPoint',
       'AttachTrigger',
       'AutoAimSize',
       'AutoAimYLimits',
       'AutoFire',
       'AvailableForAnyTeam',
       'BallAcceleration',
       'BallCollision',
       'BallLowResModel',
       'BallMaxLean',
       'BallMinMoveSpeed',
       'BallMoveSpeed',
       'BallMoveThreshold',
       'BallRadius',
       'BallRollingFriction',
       'BallSlippage',
       'BallTurnSpeed',
       'BallWaterDamageHeight',
       'BankAngle',
       'BankFilter',
       'BarrelLength',
       'BarrelNodeName',
       'BarrelRecoil',
       'BeamIntensity',
       'BlurEffect',
       'BlurLength',
       'BlurStart',
       'BodyOmegaXSpringFactor',
       'BodySpringLength',
       'BoostSound',
       'BoxSize',
       'BuildAnimation',
       'BuildingAmmo',
       'BuildingBuild',
       'BuildingCollision',
       'BuildingCollisionPrim',
       'BuildingHealth',
       'BuildingRebuild',
       'BuildingScale',
       'BUILDINGSECTION',
       'BuildModelOdf',
       'BuildPoint',
       'BuiltCollision',
       'BuiltSound',
       'CableLength',
       'CameraDistance',
       'CameraHeight',
       'CAMERASECTION',
       'CanDeflect',
       'CapturedSound',
       'CapturePosts',
       'CaptureRegion',
       'CaptureTime',
       'CargoNodeName',
       'ChangeModeSound',
       'ChargeDelayHeavy',
       'ChargeDelayLight',
       'ChargeRateHeavy',
       'ChargeRateLight',
       'ChargeSound',
       'ChargeSoundPitch',
       'ChargeUpEffect',
       'ChunkAngularDamping',
       'ChunkBounciness',
       'ChunkDeathSpeed',
       'ChunkFrequency',
       'ChunkGeometryName',
       'ChunkLinearDamping',
       'ChunkNodeName',
       'ChunkOmega',
       'ChunkPhysics',
       'CHUNKSECTION',
       'ChunkSimpleFriction',
       'ChunkSmokeEffect',
       'ChunkSmokeNodeName',
       'ChunkSpeed',
       'ChunkStartDistance',
       'ChunkStickiness',
       'ChunkTerrainCollisions',
       'ChunkTerrainEffect',
       'ChunkTrailEffect',
       'ChunkUpFactor',
       'ChunkVelocityFactor',
       'CisMusic',
       'CISMusic',
       'ClankLeftRunSound',
       'ClankLeftWalkSound',
       'ClankRightRunSound',
       'ClankRightWalkSound',
       'ClassAllATK',
       'ClassAllDEF',
       'ClassCISATK',
       'ClassCISDEF',
       'ClassHisATK',
       'ClassHisDEF',
       'ClassImpATK',
       'ClassImpDEF',
       'classLabel',
       'ClassLabel',
       'ClassLocATK',
       'ClassLocDEF',
       'ClassRepATK',
       'ClassRepDEF',
       'CloseSound',
       'ClothingRustleSound',
       'cmd_lclick',
       'cmd_lhold',
       'cmd_rclick',
       'cmd_rhold',
       'CockedAngle',
       'CockpitChatterStream',
       'CockpitTension',
       'CodeInitialWidth',
       'Collision',
       'COLLISION',
       'CollisionInflict',
       'CollisionLowResRootScale',
       'collisionName',
       'CollisionOtherSound',
       'CollisionRootScale',
       'CollisionScale',
       'CollisionSound',
       'CollisionThreshold',
       'Color',
       'ConeAngle',
       'ConeFadeFactor',
       'ConeFadeLength',
       'ConeHeight',
       'ConeInitialWidth',
       'ConeLength',
       'ConeWidth',
       'Controllable',
       'ControlRegion',
       'ControlZone',
       'CrouchMoveSpread',
       'CrouchStillSpread',
       'Damage',
       'DamageAttachPoint',
       'DamageDeduction',
       'DamageEffect',
       'DamageEffectScale',
       'DamageInheritVelocity',
       'DamageRadius',
       'DamageRadiusInner',
       'DamageRadiusOuter',
       'DamageStartPercent',
       'DamageStopPercent',
       'DamageThreshold',
       'DarknessMax',
       'DarknessMin',
       'DeathAnimation',
       'DeathAnimationExplosion',
       'DeathAnimationExplosionTime',
       'DeathDustDelay',
       'DeathDustEffect',
       'DeathDustOffset',
       'DeathEffect',
       'DeathEffectOffset',
       'DeathOnCollision',
       'DeathShakeDelay',
       'DeathShakeDuration',
       'DeathShakeForce',
       'DeathShakeRadius',
       'DeathSound',
       'DeathTime',
       'Decal',
       'DecayTime',
       'Deceleration',
       'DeflectSound',
       'DenyFlyerLand',
       'deploy',
       'DestroyedGeometryName',
       'DetatchSound',
       'DisableForCloneWars',
       'DisableTime',
       'Discharge',
       'DischargeSound',
       'DisguiseOwnerModel',
       'DisputeSound',
       'DroidHealth',
       'DroidScale',
       'DropItemClass',
       'DropItemProbability',
       'DropShadowSize',
       'Effect',
       'EffectRegion',
       'eject',
       'Emitter',
       'EnableDeathExplosions',
       'EnemyColor',
       'EngineSound',
       'ExpireEffect',
       'ExpireTimeEnemy',
       'ExpireTimeField',
       'Explosion',
       'ExplosionClass',
       'ExplosionCritical',
       'ExplosionDeath',
       'ExplosionDestruct',
       'ExplosionExpire',
       'ExplosionImpact',
       'ExplosionName',
       'ExplosionOffset',
       'ExplosionTrigger',
       'ExtremeRange',
       'EyePointCenter',
       'EyePointOffset',
       'FadeOutTime',
       'FinalExplosion',
       'FinalExplosionOffset',
       'FinAnimation',
       'FireAnim',
       'FireEmptySound',
       'FireLoopSound',
       'FireNodeName',
       'FireOutsideLimits',
       'FirePoint',
       'FirePointName',
       'FireSound',
       'FireSoundStop',
       'FireStateTime',
       'FireVelocity',
       'FirstPerson',
       'FirstPersonFOV',
       'FirstRadius',
       'FlareAngle',
       'FlareIntensity',
       'FlashColor',
       'FlashLength',
       'FlashLightColor',
       'FlashLightDuration',
       'FlashLightRadius',
       'FlatCount',
       'FlatFaceFactor',
       'FlatGrassSwing',
       'FlatHeight',
       'FlatSizeMultiplier',
       'FleeSound',
       'FlickerPeriod',
       'FlickerType',
       'FlyerBan',
       'FLYERSECTION',
       'FoleyFXClass',
       'FoleyFXGroup',
       'FootBoneLeft',
       'FootBoneRight',
       'Footstep0Sound',
       'Footstep1Sound',
       'Footstep2Sound',
       'FootstepSound0',
       'FootstepSound1',
       'FootStepSound1',
       'FootstepSound2',
       'FootStepSound2',
       'FootstepSound3',
       'FootstepSound4',
       'FootstepSound5',
       'FootWaterSplashEffect',
       'ForceFireAnimation',
       'ForceMode',
       'ForwardSpeed',
       'ForwardTurnSpeed',
       'Friction',
       'FriendlyColor',
       'frontal_target',
       'FXName',
       'GeometryAddon',
       'GeometryColorMax',
       'GeometryColorMin',
       'GeometryLowRes',
       'geometryName',
       'GeometryName',
       'geometryScale',
       'GeometryScale',
       'GlowLength',
       'Gravity',
       'GravityScale',
       'GroundedHeight',
       'GroundedSound',
       'HealthScale',
       'HealthSScale',
       'HealthStatusTexture',
       'HealthTexture',
       'Healthtype',
       'HealthType',
       'HeardEnemySound',
       'HeatPerShot',
       'HeatRecoverRate',
       'HeatThreshold',
       'Height',
       'HeightScale',
       'HideHealthBar',
       'HideOnFire',
       'HideUnbuiltModel',
       'HidingSound',
       'HierarchyLevel',
       'HighResGeometry',
       'HitLocation',
       'HitSound',
       'HoloBeamIntensity',
       'HoloFadeInTime',
       'HoloFlareIntensity',
       'HoloFlickerAlphaMax',
       'HoloFlickerAlphaMin',
       'HoloFlickerRate',
       'HoloHeight',
       'HoloImageGeometry',
       'HoloImageIntensity',
       'HoloLightIntensity',
       'HoloLightRadius',
       'HoloOdf',
       'HoloPopRate',
       'HoloRotateRate',
       'HoloSize',
       'HoloTurnOnTime',
       'HoloType',
       'HoloVisibleDistance',
       'HorizontalSpread',
       'HoverBan',
       'HugeBan',
       'HurtSound',
       'HydraulicLowerHeight',
       'HydraulicLowerSound',
       'HydraulicSound',
       'HydraulicSoundHeight',
       'IconStatusTexture',
       'IconTexture',
       'IdleAnimation',
       'IdleDelay',
       'IdleRotateSpeed',
       'IdleWaitTime',
       'IdleWobbleFactor',
       'IdleWobbleLeftFoot',
       'IdleWobbleNode',
       'IdleWobbleRightFoot',
       'IgnorableCollsion',
       'ImpactEffect',
       'ImpactEffectRigid',
       'ImpactEffectShield',
       'ImpactEffectSoft',
       'ImpactEffectStatic',
       'ImpactEffectTerrain',
       'ImpactEffectWater',
       'ImpMusic',
       'InitialCableLength',
       'InitialSalvoDelay',
       'InputSystem',
       'InstanceProperties',
       'IsPilotExposed',
       'JetDuration',
       'JetEffect',
       'JetFuelCost',
       'JetFuelInitialCost',
       'JetFuelMinBorder',
       'JetFuelRechargeRate',
       'JetJump',
       'JetPush',
       'JetType',
       'jump',
       'JumpDeduction',
       'JumpSound',
       'KickBuildup',
       'KickSpread',
       'KickStrength',
       'KillRegion',
       'KillSoldierSound',
       'Label',
       'LandedHeight',
       'LandingSpeed',
       'LandingTime',
       'LandSound',
       'LaserGlowColor',
       'LaserLength',
       'LaserTexture',
       'LaserWidth',
       'LeftFootstepSound',
       'LegBoneLeft',
       'LegBoneRight',
       'LegBoneTopLeft',
       'LegBoneTopRight',
       'LegPairCount',
       'LegRayHitLength',
       'LevelDamp',
       'LevelFilter',
       'LevelSpring',
       'Lifespan',
       'LifeSpan',
       'LiftDamp',
       'LiftSpring',
       'LightColor',
       'LightDuration',
       'Lighting',
       'LightningEffect',
       'LightRadius',
       'lights',
       'LocalsColor',
       'LockedOnSound',
       'LockedSound',
       'LockOffAngle',
       'lockOnAngle',
       'LockOnAngle',
       'LockOnRange',
       'LockOnTime',
       'LockTime',
       'LostSound',
       'LowHealthSound',
       'LowHealthThreshold',
       'LowResModel',
       'MapScale',
       'MapTexture',
       'MaxAlpha',
       'MaxBallAngle',
       'MaxChargeStrengthHeavy',
       'MaxChargeStrengthLight',
       'MaxDamage',
       'MaxDelayHeavy',
       'MaxDelayLight',
       'MaxDistance',
       'MaxFallingLeaves',
       'MaxHealth',
       'MaxHeavy',
       'MaxHeavyDecay',
       'MaxInterval',
       'MaxItems',
       'MaxJumpDistance',
       'MaxLifetime',
       'MaxLifeTime',
       'MaxLight',
       'MaxLightDecay',
       'MaxPitchSpeed',
       'MaxPos',
       'MaxPressedTime',
       'MaxPush',
       'MaxRange',
       'MaxScatterBirds',
       'MaxShakeAmt',
       'MaxShakeLen',
       'MaxShield',
       'MaxSize',
       'MaxSkew',
       'MaxSpeed',
       'MaxSpread',
       'MaxStrafeSpeed',
       'MaxStrength',
       'MaxTargets',
       'MaxTerrainAngle',
       'MaxTimeLeftHeavy',
       'MaxTimeLeftLight',
       'MaxTurnSpeed',
       'MaxVel',
       'MaxYawSpeed',
       'MediumBan',
       'MidSpeed',
       'MinAlpha',
       'MinDamage',
       'MinDelayHeavy',
       'MinDelayLight',
       'MinDistance',
       'MinEnemyRadius',
       'MinHeavy',
       'MinHeavyDecay',
       'MinInterval',
       'MinLifetime',
       'MinLifeTime',
       'MinLight',
       'MinLightDecay',
       'MinPos',
       'MinPush',
       'MinRange',
       'MinShakeAmt',
       'MinShakeLen',
       'MinSize',
       'MinSpeed',
       'MinSpread',
       'MinStrength',
       'MinTimeLeftHeavy',
       'MinTimeLeftLight',
       'MinVel',
       'ModeTexture',
       'ModeTextureColor',
       'MountPos',
       'MoveTension',
       'MoveTensionX',
       'MoveTensionY',
       'MoveTensionZ',
       'MovingTurnOnly',
       'Music',
       'MusicDelay',
       'MusicSpeed',
       'MuzzleFlash',
       'MuzzleFlashEffect',
       'NeutralColor',
       'NeutralizeTime',
       'NextAimer',
       'NextBarrel',
       'NextCharge',
       'NEXTCHARGE',
       'NextDropItem',
       'NoCombatInterrupt',
       'NoDeathExplosions',
       'NoEnterVehicles',
       'NoRandomSpring',
       'NormalDirection',
       'NumChunks',
       'NumDustObjectsInEffects',
       'NumParticles',
       'NumParts',
       'NumRays',
       'NumVisible',
       'Odf',
       'Offset',
       'OmegaXDamp',
       'OmegaXSpring',
       'OmegaZDamp',
       'OmegaZSpring',
       'OmniLightRadius',
       'OmniRadius',
       'OpenSound',
       'OptimalRange',
       'OrdnanceClass',
       'Ordnancecollision',
       'OrdnanceCollision',
       'OrdnanceCollisionPrim',
       'OrdnanceEffect',
       'OrdnanceGeometryName',
       'OrdnanceName',
       'OrdnanceSound',
       'OverheatSound',
       'OverheatSoundPitch',
       'OverheatStopSound',
       'OverrideTexture',
       'OverrideTexture2',
       'PCaxPitchSpeed',
       'PCMaxPitchSpeed',
       'PCMaxStrafeSpeed',
       'PCMaxTurnSpeed',
       'PCMaxYawSpeed',
       'PCPitchRate',
       'PCPitchSpeed',
       'PCPitchTurnFactor',
       'PCSpinRate',
       'PCTurnRate',
       'PCTurnSpeed',
       'PCYawTurnFactor',
       'PersonHealth',
       'PersonScale',
       'Pilot9Pose',
       'PilotAnimation',
       'PilotPosition',
       'PilotSkillRepairScale',
       'PilotType',
       'pitch_down',
       'pitch_up',
       'pitch',
       'PitchDamp',
       'PitchFilter',
       'PitchLimits',
       'PitchRate',
       'PitchSpread',
       'PitchTurnFactor',
       'PowerupDelay',
       'Powerupsound',
       'PPitchRate',
       'PreparingForDamageSound',
       'PrimaryWeapon',
       'ProneMoveSpread',
       'ProneSound',
       'ProneStillSpread',
       'Push',
       'PushDeduction',
       'PushRadius',
       'PushRadiusInner',
       'PushRadiusOuter',
       'Radius',
       'RadiusFadeMax',
       'RadiusFadeMin',
       'Range',
       'RayRadius',
       'RayTriggerMinSpeed',
       'RayTriggerWidth',
       'Rebound',
       'RecoilDecayHeavy',
       'RecoilDecayLight',
       'RecoilDelayHeavy',
       'RecoilDelayLight',
       'RecoilLengthHeavy',
       'RecoilLengthLight',
       'RecoilStrengthHeavy',
       'RecoilStrengthLight',
       'RefillFromItem',
       'ReloadSound',
       'ReloadTime',
       'RepMusic',
       'ReserveOneForPlayer',
       'ResetTeam',
       'RespawnTime',
       'RestDir',
       'ReticuleTexture',
       'ReverseSpeed',
       'RightFootstepSound',
       'RollSound',
       'Rotation',
       'RotationRate',
       'RotationVelocity',
       'RoundDelay',
       'RoundsPerClip',
       'RoundsPersalvo',
       'RoundsPerSalvo',
       's',
       'SalvoCount',
       'SalvoDelay',
       'SalvoTime',
       'ScanningRange',
       'ScatterDistance',
       'SCDriverGetInSound',
       'SCDriverGetOutSound',
       'SCFieldFollowSound',
       'SCFieldHoldSound',
       'SCFieldMoveOutSound',
       'SCGunnerAllClearSound',
       'SCGunnerGetInSound',
       'SCGunnerGetOutSound',
       'SCGunnerSteadySound',
       'ScopeTexture',
       'SCPassengerGetInSound',
       'SCPassengerGetOutSound',
       'SCPassengerMoveOutSound',
       'SCPassengerStopSound',
       'SCResponseNosirSound',
       'SCResponseYessirSound',
       'SecondaryWeapon',
       'Seed',
       'SelfDestructSoundPitch',
       'SetAltitude',
       'Shake',
       'ShakeLength',
       'ShakeRadius',
       'ShakeRadiusInner',
       'ShakeRadiusOuter',
       'ShieldEffect',
       'ShieldOffset',
       'ShieldOffSound',
       'ShieldRadius',
       'ShieldScale',
       'ShieldSound',
       'ShockFadeInTime',
       'ShockFadeOutGain',
       'ShockFadeOutTime',
       'ShockSound',
       'shotdelay',
       'ShotDelay',
       'ShotElevate',
       'ShotPatternCount',
       'ShotPatternPitchYaw',
       'ShotsPerSalvo',
       'SkeletonLowRes',
       'SkeletonLowResRootScale',
       'SkeletonName',
       'SkeletonRootScale',
       'SkeletonRootScaleLowRes',
       'SkinnyFactor',
       'SmallBan',
       'SmashParkedFlyers',
       'SniperScope',
       'SoldierAmmo',
       'SoldierAnimation',
       'SoldierBan',
       'soldierCollision',
       'Soldiercollision',
       'SoldierCollision',
       'SoldierCollisionOnly',
       'SoldierCollisionPrim',
       'SoldierHealth',
       'Sound',
       'SoundName',
       'SoundPitchDev',
       'SoundProperty',
       'SpawnPath',
       'SpawnPointCount',
       'SpawnPointLocation',
       'SpawnSound',
       'SpawnTime',
       'SpinRate',
       'SpreadLimit',
       'SpreadPerShot',
       'SpreadRadius',
       'SpreadRecover',
       'SpreadRecoverRate',
       'SpreadThreshold',
       'SquatSound',
       'StandMoveSpread',
       'StandSound',
       'StandStillSpread',
       'static',
       'Static',
       'StatusTexture',
       'steer_left',
       'steer_right',
       'steer',
       'StickAnimal',
       'StickBuilding',
       'StickBuildingDead',
       'StickBuildingUnbuilt',
       'StickDroid',
       'StickPerson',
       'StickTerrain',
       'StickVehicle',
       'StompDecal',
       'StompDecalSize',
       'StompDetectionType',
       'StompEffect',
       'StompThreshold',
       'StoppedTurnSpeed',
       'strafe_left',
       'strafe_right',
       'strafe',
       'StrafeRollAngle',
       'StrafeSpeed',
       'Strategic_Filter1',
       'Strategic_Filter2',
       'Strategic_Filter3',
       'Strategic_Filter4',
       'Strategic_Filter5',
       'Strategic_Filter6',
       'StrikeOrdnanceName',
       'SuppressRadius',
       'SuspensionLeftArmNodeName',
       'SuspensionMaxOffset',
       'SuspensionMidOffset',
       'SuspensionNodeName',
       'SuspensionRightArmNodeName',
       'SwingSpeed',
       'SwingTime',
       'SwitchImmediately',
       'TakeoffHeight',
       'TakeoffSound',
       'TakeoffSpeed',
       'TakeoffTime',
       'TargetableCollision',
       'TargetAnimal',
       'TargetBuilding',
       'TargetDroid',
       'TargetEnemy',
       'TargetFriendly',
       'TargetNeutral',
       'TargetPerson',
       'TargetVehicle',
       'TEMP_AnimationSpeed',
       'TEMP_Type',
       'TerrainCollision',
       'TerrainCollisionPrim',
       'TerrainLeft',
       'TerrainRight',
       'Texture',
       'ThirdPersonFOV',
       'throttle_down',
       'throttle_up',
       'throttle',
       'ThrustAttachOffset',
       'ThrustAttachPoint',
       'ThrustEffect',
       'ThrustEffectMaxScale',
       'ThrustEffectMinScale',
       'ThrustEffectScaleStart',
       'ThrustPitchAngle',
       'TickSound',
       'TickSoundPitch',
       'TiltValue',
       'TowCableCollision',
       'track_pitch_minus',
       'track_pitch_plus',
       'track_pitch_reset',
       'track_yaw_minus',
       'track_yaw_plus',
       'track_yaw_reset',
       'TrackCenter',
       'TrackDeathOnAttach',
       'TrackingSound',
       'TrackOffset',
       'Traction',
       'TrailEffect',
       'TrakCenter',
       'TransmitRange',
       'TransparentType',
       'TrialEffect',
       'TriggerAll',
       'TriggerAnimation',
       'TriggerCollision',
       'TriggerContact',
       'TriggerOffset',
       'TriggerRadius',
       'TriggerSingle',
       'TriggerTeam',
       'TurnFilter',
       'TurningOffSound',
       'TurnOffSound',
       'TurnOffTime',
       'TurnOnSound',
       'TurnOnTime',
       'TurnRate',
       'TurnThreshold',
       'TurretActivateSound',
       'TurretAmbientSound',
       'TurretDeactivateSound',
       'TurretMoveSound',
       'TurretMoveSoundStartEndPitch',
       'TurretMoveSoundStartEndTime',
       'TurretNodeName',
       'TurretPitchSound',
       'TurretPitchSoundPitch',
       'TURRETSECTION',
       'TurretStartSound',
       'TurretStopSound',
       'TurretYawSound',
       'TurretYawSoundPitch',
       'UnbuiltGeometryName',
       'UnbuiltHoloOdf',
       'unitName',
       'UnitType',
       'UprightLowResModel',
       'UprightWaterDamageHeight',
       'UseVCollForFlyers',
       'Value_ATK_Alliance',
       'Value_ATK_CIS',
       'Value_ATK_Empire',
       'Value_ATK_Locals',
       'Value_ATK_Republic',
       'Value_DEF_Alliance',
       'Value_DEF_CIS',
       'Value_DEF_Empire',
       'Value_DEF_Locals',
       'Value_DEF_Republic',
       'ValueBleed',
       'VehicleAmmo',
       'vehiclecollision',
       'Vehiclecollision',
       'VehicleCollision',
       'vehiclecollisiononly',
       'VehicleCollisiononly',
       'VehicleCollisionOnly',
       'VehicleCollisionPrim',
       'VehicleCollisionSound',
       'VehicleHealth',
       'VehiclePosition',
       'VehicleScale',
       'VehicleType',
       'Velocity',
       'VelocityDamp',
       'VelocitySpring',
       'VerticalSpread',
       'Vine',
       'Virtual',
       'VO_All_AllCapture',
       'VO_All_AllInDispute',
       'VO_All_AllInfo',
       'VO_All_AllLost',
       'VO_All_AllSaved',
       'VO_All_ImpCapture',
       'VO_All_ImpInDispute',
       'VO_All_ImpInfo',
       'VO_All_ImpLost',
       'VO_All_ImpSaved',
       'VO_CIS_CISCapture',
       'VO_CIS_CISInDispute',
       'VO_CIS_CISInfo',
       'VO_CIS_CISLost',
       'VO_CIS_CISSaved',
       'VO_CIS_RepCapture',
       'VO_CIS_RepInDispute',
       'VO_CIS_RepInfo',
       'VO_CIS_RepLost',
       'VO_CIS_RepSaved',
       'VO_Imp_AllCapture',
       'VO_Imp_AllInDispute',
       'VO_Imp_AllInfo',
       'VO_Imp_AllLost',
       'VO_Imp_AllSaved',
       'VO_Imp_ImpCapture',
       'VO_Imp_ImpInDispute',
       'VO_Imp_ImpInfo',
       'VO_Imp_ImpLost',
       'VO_Imp_ImpSaved',
       'VO_Rep_CISCapture',
       'VO_Rep_CISInDispute',
       'VO_Rep_CISInfo',
       'VO_Rep_CISLost',
       'VO_Rep_CISSaved',
       'VO_Rep_RepCapture',
       'VO_Rep_RepInDispute',
       'VO_Rep_RepInfo',
       'VO_Rep_RepLost',
       'VO_Rep_RepSaved',
       'WakeEffect',
       'WakeWaterSplashEffect',
       'WalkerLegPair',
       'WalkerOrientRoll',
       'WALKERSECTION',
       'WalkerWidth',
       'WaterDamageAmount',
       'WaterDamageInterval',
       'WaterEffect',
       'WaterSplashEffect',
       'WaterWadingSound',
       'WaverRate',
       'WaverTurn',
       'weapon_fire',
       'weapon_next',
       'weapon_prev',
       'weapon_special',
       'WeaponAmmo',
       'WeaponAmmo1',
       'WeaponAmmo2',
       'WeaponAmmo3',
       'WeaponAmmo4',
       'WeaponChange',
       'WeaponChangeSound',
       'WeaponChannel',
       'WeaponChannel1',
       'WeaponChannel2',
       'WeaponChannel3',
       'WeaponChannel4',
       'WeaponClass',
       'WeaponName',
       'WeaponName1',
       'WeaponName2',
       'WeaponName3',
       'WeaponName4',
       'WeaponSection',
       'WEAPONSECTION',
       'WiggleAmount',
       'WiggleSpeed',
       'WindSound',
       'WingModel',
       'YawLimits',
       'YawSpread',
       'YawTurnFactor',
       'YOffset',
       'zoom_factor_minus',
       'zoom_factor_plus',
       'zoom_factor_reset',
       'ZoomFirstPerson',
       'ZoomMax',
       'ZoomMin',
       'ZoomRate',
    ]

    def __init__(self, filepath: Path, tokens: list[Token]):
        Document.__init__(self, filepath=filepath)
        Parser.__init__(self, filepath=filepath, tokens=tokens)

        self.curr = self

    @staticmethod
    def read(filename: str = None, filepath: Path = None, file: FileIO = None, stream: StringIO = None) -> Document:
        lexer = Lexer(filename, filepath, file, stream)
        tokens: list[Token] = lexer.tokenize()

        odf = ODF(filepath, tokens)

        logger.debug(f'Process {filepath}')

        while odf:
            if odf.get().type in TK.Whitespaces:
                odf.discard()  # Discard whitespaces at the start of a line

            # Comment
            elif odf.get().type in [TK.Slash, TK.Backslash]:
                odf.consume_until(TK.LineFeed)

                comment = Comment(odf.collect_tokens())
                odf.curr.add(comment)

                odf.discard()  # \n

            # Section
            elif odf.get().type == TK.SquareBracketOpen:
                odf.discard()  # [

                odf.consume_until(TK.SquareBracketClose)

                if odf.curr != odf:
                    odf.curr = odf.curr.parent

                section = Section(odf.collect_tokens())
                odf.curr = section
                odf.add(section)

                odf.discard()  # ]

            # Key value pair
            elif odf.get().type == TK.Word:
                while odf.consume(TK.Word):
                    pass

                key = Key(odf.collect_tokens())
                odf.curr.add(key)

                while odf.consume_any([TK.EqualSign] + TK.Whitespaces):
                    pass

                odf.collect_tokens()  # Discard whitespaces and '=' between key and value

                odf.consume_until(TK.LineFeed)

                value = Value(odf.collect_tokens())
                odf.curr.add(value)

                odf.discard()  # \n

            # Either skip or thow error
            else:
                logger.warning(f'Unrecognized token "{odf.get()} ({odf.tokens()})".')
                odf.discard()
                # odf.error(TK.Null)

        return odf


if __name__ == '__main__':
    if len(sys.argv) == 2:
        path = Path(sys.argv[1])
        if path.is_file():
            odf = ODF.read(filepath=path)
        else:
            for file in path.rglob('*.odf'):
                odf = ODF.read(filepath=file)

    elif len(sys.argv) > 2:
        odf = ODF.read(stream=sys.stdin)
    else:
        sys.exit(1)

    # TODO: Global exit code
    sys.exit(0)
