name: Build-Docs

on:
  push:
    branches: ["*"]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      DIR_BUILD: ${{ github.workspace }}/build
      DIR_CODE: ${{ github.workspace }}/code
      DIR_DOCS: ${{ github.workspace }}/docs
      DIR_HTML_TEMPLATES: ${{ github.workspace }}/code/resource/html/templates
      DIR_HTML_ASSETS: ${{ github.workspace }}/code/resource/html/assets
      DIR_RESOURCE: ${{ github.workspace }}/code/resource
      DIR_SOURCE: ${{ github.workspace }}/code/source
      BRANCH: ${{ github.head_ref || github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Setup
      run: python -m pip install -r ${{ env.DIR_CODE }}/requirements.txt

    - name: Build
      run: |
        python ${{ env.DIR_SOURCE }}/main.py -f ${{ env.DIR_DOCS }} \
          HTML -c -d ${{ env.DIR_BUILD }} -t ${{ env.DIR_HTML_TEMPLATES }} -a ${{ env.DIR_HTML_ASSETS }}

    - name: Upload Build Results
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ env.BRANCH }}-${{ github.sha }}
        path: ${{ env.DIR_BUILD }}
        retention-days: 7

    - name: Upload Build Results
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ env.BRANCH }}-${{ github.sha }}
        path: ${{ env.DIR_BUILD }}
        retention-days: 7

    - name: Upload Build Results for pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ${{ env.DIR_BUILD }}
        retention-days: 7

  deploy:
    runs-on: ubuntu-latest

    needs: main

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4